eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  payment-service:
    endpoints:
      getByOrderId:
        uri: http://payment-service/payments/{orderId}
      create:
        uri: http://payment-service/payments
  order-service:
    endpoints:
      create:
        uri: http://order-service/orders
